version: '3.8'

services:
  dune-drops-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dune-drops-tracker
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
      - HOSTNAME=0.0.0.0
      # Pass through Twitch API credentials from host environment
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    restart: unless-stopped
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3010/api/streamers"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
